// <auto-generated />
using CP.Api.Gerenciamento.Procedimentos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CP.Api.Gerenciamento.Procedimentos.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CP.Api.Gerenciamento.Procedimentos.Models.Procedimento", b =>
                {
                    b.Property<int>("IDProcedimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DuracaoProcedimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProcedimento")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("valorProcedimento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProcedimento");

                    b.ToTable("Procedimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
